(function() {var implementors = {
"db_handling":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"db_handling/enum.Error.html\" title=\"enum db_handling::Error\">Error</a>"]],
"defaults":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"defaults/enum.Error.html\" title=\"enum defaults::Error\">Error</a>"]],
"definitions":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"definitions/error_active/enum.Wasm.html\" title=\"enum definitions::error_active::Wasm\">Wasm</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"definitions/error/enum.MetadataError.html\" title=\"enum definitions::error::MetadataError\">MetadataError</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"definitions/error/enum.Error.html\" title=\"enum definitions::error::Error\">Error</a>"]],
"generate_message":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"generate_message/parser/enum.Set.html\" title=\"enum generate_message::parser::Set\">Set</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"generate_message/parser/enum.Goal.html\" title=\"enum generate_message::parser::Goal\">Goal</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"generate_message/enum.Error.html\" title=\"enum generate_message::Error\">Error</a>"]],
"navigator":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"navigator/enum.Error.html\" title=\"enum navigator::Error\">Error</a>"]],
"parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"parser/enum.Error.html\" title=\"enum parser::Error\">Error</a>"]],
"qr_reader_phone":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"qr_reader_phone/enum.Error.html\" title=\"enum qr_reader_phone::Error\">Error</a>"]],
"signer":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"signer/enum.ErrorDisplayed.html\" title=\"enum signer::ErrorDisplayed\">ErrorDisplayed</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"signer/enum.QrSequenceDecodeError.html\" title=\"enum signer::QrSequenceDecodeError\">QrSequenceDecodeError</a>"]],
"transaction_parsing":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"transaction_parsing/enum.Error.html\" title=\"enum transaction_parsing::Error\">Error</a>"]],
"transaction_signing":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.0/core/fmt/trait.Display.html\" title=\"trait core::fmt::Display\">Display</a> for <a class=\"enum\" href=\"transaction_signing/enum.Error.html\" title=\"enum transaction_signing::Error\">Error</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()