'use strict'

export const ADD_ACCOUNT = 'ACCOUNT_ACTION_ADD_ACCOUNT'
export const SELECT_ACCOUNT = 'ACCOUNT_ACTION_SELECT_ACCOUNT'
export const DELETE_ACCOUNT = 'ACCOUNT_ACTION_DELETE_ACCOUNT'
export const MODIFY_ACCOUNT = 'ACCOUNT_ACTION_MODIFY_ACCOUNT'
export const SET_PIN = 'ACCOUNT_ACTION_SET_PIN'
export const SET_ACCOUNTS = 'ACCOUNT_ACTION_SET_ACCOUNTS'
