// This file is automatically generated, please do not modify

import * as metadata from 'constants/networkMetadata';

export const defaultPolkadotMetaData = metadata.polkadotMetadataV30;

export const defaultMetaData = metadata.kusamaMetadataV9030;

export const allBuiltInMetadata = [
	metadata.kulupuMetadataV17,
	metadata.centrifugeMetadata,
	metadata.centrifugeAmberMetadata,
	metadata.polkadotMetadataV30,
	metadata.edgewareMetadata,
	metadata.rococoMetadataV9002,
	metadata.kusamaMetadataV9030,
	metadata.westendMetadataV9033,
	metadata.polkadotMetadataV29,
	metadata.rococoMetadataV9001,
	metadata.kusamaMetadataV9010,
	metadata.westendMetadataV9030,
];
