export type RootStackParamList = {
	Wallet: undefined;
	AddNetwork: { isNew: boolean } | undefined;
	ShowRecoveryPhrase: { seedPhrase: string };
	RenameWallet: { identity };
	DeleteWallet: { identity };
	CreateWallet: undefined;
	CreateWallet2: undefined;
	CreateWallet3: { seedPhrase: string };
	CreateWalletImport: undefined;
	Settings: undefined;
	MessageDetails: undefined;
	Empty: undefined;
	ReceiveBalance: { path: string };
	SendBalance: { path: string };
	Security: undefined;
	SignTransaction: { isScanningNetworkSpec: true } | undefined;
	SignTransactionFinish: undefined;
	TxDetails: undefined;
};
