name: 'Install Android Dependencies'
description: 'Sets up JDK and Android SDK/NDK'

runs:
  using: "composite"
  steps:
    - name: Set up JDK environment
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: 17

    - name: Setup Android SDK
      shell: bash
      run: |
        mkdir -p /opt/android-sdk
        export ANDROID_SDK_ROOT=/opt/android-sdk
        echo "ANDROID_SDK_ROOT=/opt/android-sdk" >> $GITHUB_ENV
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d $ANDROID_SDK_ROOT
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        mv $ANDROID_SDK_ROOT/cmdline-tools/* $ANDROID_SDK_ROOT/cmdline-tools/latest/ || true
        rm -rf $ANDROID_SDK_ROOT/cmdline-tools/latest/cmdline-tools
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install NDK
      shell: bash
      run: echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;24.0.8215888" --sdk_root=${ANDROID_SDK_ROOT}
