plugin 'firebase_app_distribution'
opt_out_usage
default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"

platform :ios do
  # imports
  import ("lanes/lane_tests.rb")
  import ("lanes/lane_build.rb")
  import ("lanes/lane_testflight.rb")
  import ("lanes/lane_appstore.rb")
  import ("lanes/lane_firebase.rb")

  # shared variables
  main_target = "PolkadotVault"

  test_scheme = "PolkadotVault-Dev"

  distribution_scheme = "PolkadotVault"
  distribution_configuration = "Release"

  distribution_qa_scheme = "PolkadotVault-QA"
  distribution_qa_configuration = "QA"

  desc "Runs unit tests for development scheme"
  desc "Example usage: fastlane run_unit_tests"
  lane :run_unit_tests do
    test_build(
      scheme:test_scheme
    )
  end

  desc "Distribute new iOS production build through TestFlight"
  desc "Example usage: fastlane distribute_production_testflight"
  lane :distribute_production_testflight do
    load_asc_api_key
    prepare_code_signing(
    	type: "appstore"
    )
    build_release(
      scheme:distribution_scheme,
      target:main_target,
      configuration:distribution_configuration,
      profile_name:"match AppStore io.parity.NativeSigner",
      export_method: "app-store"
    )
    upload_testflight
  end

  desc "Distribute new iOS QA build through TestFlight"
  desc "Example usage: fastlane distribute_qa_testflight"
  lane :distribute_qa_testflight do
    load_asc_api_key
    prepare_code_signing(
      type: "appstore"
    )
    build_release(
      scheme:distribution_qa_scheme,
      target:main_target,
      configuration:distribution_qa_configuration,
      profile_name:"match AppStore io.parity.NativeSigner",
      export_method: "app-store"
    )
    upload_testflight
  end
  

  desc "Distribute new iOS QA build through Firebase"
  desc "Example usage: fastlane distribute_qa_firebase"
  lane :distribute_qa_firebase do
    load_asc_api_key
    prepare_code_signing(
    	type: "adhoc"
    )
    build_release(
      scheme:distribution_qa_scheme,
      target:main_target,
      configuration:distribution_qa_configuration,
      profile_name:"match AdHoc io.parity.NativeSigner",
      export_method: "ad-hoc"
    )
    upload_firebase
  end
  
end
