package io.parity.signer.domain

import android.content.Context
import android.graphics.BitmapFactory
import timber.log.Timber
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.asImageBitmap
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.mapLatest
import kotlinx.coroutines.flow.stateIn
import java.io.File

typealias Callback = () -> Unit



/**
 * Decodes from hex string into number array
 */
fun String.decodeHex(): ByteArray {
	return chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}

/**
 * Replace middle of long string with "..."
 * length: number of symbols to keep on either side
 * if message is too short, does not modify it
 */
fun String.abbreviateString(length: Int): String {
	return if (this.length > length * 2) {
		this.substring(0, length) + "..." + this.substring(
			this.length - length,
			this.length
		)
	} else {
		this
	}
}
const val BASE58_STYLE_ABBREVIATE = 8

/**
 * Encodes number array into string
 */
fun ByteArray.encodeHex(): String {
	return this.joinToString(separator = "") { byte -> "%02x".format(byte) }
}

fun <T, K> StateFlow<T>.mapState(
	scope: CoroutineScope,
	transform: (data: T) -> K
): StateFlow<K> {
	return mapLatest {
		transform(it)
	}.stateIn(scope, SharingStarted.Eagerly, transform(value))
}

/**
 * Specialized tool to decode png images generated by rust code
 */
@ExperimentalUnsignedTypes
fun List<UByte>.intoImageBitmap(): ImageBitmap {
	val picture = this.toUByteArray().toByteArray()
	return try {
		BitmapFactory.decodeByteArray(picture, 0, picture.size).asImageBitmap()
	} catch (e: java.lang.Exception) {
		Timber.d("image decoding error", e.toString())
		ImageBitmap(1, 1)
	}
}


fun Context.getDbNameFromContext(): String =
	applicationContext.filesDir.toString() + "/Database"

/**
 * We showing onboarding if db was not yet created, and this is how currently
 * different parts of the app can determine if app initialized
 */
fun Context.isDbCreatedAndOnboardingPassed(): Boolean {
	return File(getDbNameFromContext()).exists()
}
