name: Manual Firebase distribution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      firebase_group:
        description: "Firebase group"
        required: true
        default: dev-team
  push:
    branches:
      - add-firebase

jobs:
  distribute_firebase:
    #if: contains('["krodak","ERussel","stepanLav"]', github.actor)
    runs-on: macos-15
    name: Distribute Firabase QA Build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install iOS Dependencies
        uses: ./.github/actions/install-ios-dep

      - name: Write Firebase service account key
        run: |
          mkdir -p $HOME/.firebase
          echo "${{ secrets.ANDROID_FIREBASE_CREDENTIAL_FILE_CONTENT }}" > $HOME/.firebase/firebase_key.json

      - name: Distribute Firebase build
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_BASE64: ${{ secrets.ASC_KEY_BASE64 }}
          BUILD_NUMBER: $GITHUB_RUN_ID
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FIREBASE_GROUPS: ${{ github.event.inputs.firebase_group }}
          FIREBASE_RELEASE_NOTES: ${{ github.event.head_commit.message }}
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/.firebase/firebase_key.json
        run: |
          cd ios
          bundle exec fastlane distribute_qa_firebase
          rm ${GOOGLE_APPLICATION_CREDENTIALS}
