name: Manual Firebase distribution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # workflow_dispatch:
  #    inputs:
  #     firebase_group:
  #       description: 'Firebase group'
  #       required: true
  #       default: dev-team
  #     branch:
  #       description: 'From which branch the application will be built'
  #       required: true
  #       default: develop
  push:
    branches:
      - add-firebase

jobs:
  run_tests:
    name: Run tests
    uses: ./.github/workflows/reusable-android-tests.yml 
  build_apk:
    name: Build APKs
    uses: ./.github/workflows/reusable-android-build.yml
    with:
      is-release: false
  # upload_apk:
  #   runs-on: ubuntu-latest
  #   needs: [run_tests, build_apk]
  #   steps:
  #     # - uses: actions/checkout@v4
  #     - name: Download built artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: signer-unsigned-apk
  #         path: app
  #     - name: Upload to Firebase
  #       uses: novasamatech/nova-wallet-android/.github/workflows/upload-to-firebase@develop
  #       with:
  #         appId: ${{ secrets.ANDROID_DEVELOP_FIREBASE_APP_ID }}
  #         firebase-token: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
  #         releaseNotes: ${{ github.event.head_commit.message }}
  #         test-groups: ${{ github.event.inputs.firebase_group }}
  #         upload-file: app/app-develop.apk
