# Workaround for handling skipped but required checks
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name:                         Rust backend test for android

on:
  pull_request:
  push:
    branches:
      - master
      - stable
    paths:
      - 'ios/**'
      - 'android/**'

jobs:
  check:
    name:                     Cargo test on Ubuntu
    runs-on:                  ubuntu-22.04
    steps:
      - run: 'echo "No action required" '
