name:                         rustdocs

on:
  # FIXME: debug
  pull_request:
  push:
    branches:
      - master

jobs:
  rustdocs:
    name:                     Build rustdoc
    runs-on:                  ubuntu-latest
    steps:

      - name:                 Cancel Previous Runs
        uses:                 styfle/cancel-workflow-action@0.9.1
        with:
          access_token:       ${{ github.token }}

      - name:                 Checkout sources
        uses:                 actions/checkout@v3
        with:
          fetch-depth:        1
          submodules:         recursive

      - name:                 Install system dependancies
        run:                  |
          sudo apt update
          sudo apt install -y clang libclang-dev libopencv-dev

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@v1.3.0
        with:
          working-directory:  rust

      - name:                 cargo doc
        run:                  |
          cd rust
          cargo doc --all-features --verbose

      - name:                 Deploy
        uses:                 peaceiris/actions-gh-pages@v3
        with:
          github_token:       ${{ github.token }}
          publish_dir:        target/doc
