# Workaround for handling skipped but required checks
# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name:                     Check cargo deny

on:
  pull_request:
    paths:
      - '!rust/**'
      - '.github/workflows/rust-cargo-deny-skip.yml'
  push:
    branches:
      - master
      - stable
    paths:
      - '!rust/**'
      - '.github/workflows/rust-cargo-deny-skip.yml'
jobs:
  cargo-deny:
    name:                 Cargo deny
    runs-on:              ubuntu-latest
    steps:
      - run: 'echo "No action required" '
