name: Distribute TestFlight QA Build

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
 workflow_dispatch:

jobs:
  distribute_testflight:
    if: contains('["krodak","ERussel","stepanLav"]', github.actor)
    runs-on:                  macos-15
    name:                     Distribute TestFlight QA Build

    steps:

      - name:                 Checkout repository
        uses:                 actions/checkout@v4.1.1

      - name:                 Setup Ruby
        uses:                 ruby/setup-ruby@v1
        with:
          ruby-version:       '2.7'
          bundler-cache:      false

      - name:                 Setup - Xcode
        uses:                 maxim-lobanov/setup-xcode@v1
        with:
          xcode-version:      16

      - name:                 Install dependencies
        run:                  |
          brew install sourcery
          bundle install

      - name: Get cached Swift Packages managed by Xcode
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData/**/SourcePackages/
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name:                 Install Rust targets
        uses:                 dtolnay/rust-toolchain@stable
        with:
          targets:            x86_64-apple-ios,aarch64-apple-ios
          components:         rust-std

      - name:                 Install uniffi_bindgen
        uses:                 actions-rs/install@v0.1
        with:
          crate:              uniffi_bindgen
          version:            0.22.0 # Must be in sync with version in Cargo.toml
          use-tool-cache:     true

      - name:                 Rust Cache
        uses:                 Swatinem/rust-cache@27b8ea9368cf428f0bfe41b0876b1a7e809d9844 # v2.7.7
        with:
          workspaces:         rust -> rust/target

      - name:                 Distribute TestFlight build
        env:
          ASC_KEY_ID:         ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID:      ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_BASE64:     ${{ secrets.ASC_KEY_BASE64 }}
          BUILD_NUMBER:       $GITHUB_RUN_ID
          KEYCHAIN_PASSWORD:  ${{ secrets.KEYCHAIN_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
        run:                  |
          cd ios
          bundle exec fastlane distribute_qa_testflight
